# Generated by Django 5.2.8 on 2025-11-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='btu',
            new_name='btu_cooling',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='btu_heating',
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
